import { useEffect, useState } from "react";
import { marked } from "marked";
import catalog from "../../catalog.json";

// The site is a reader over catalog.json, generated by `skill-issue catalog`. It has no
// knowledge of the SKILL.md contract of its own — if the TUI and the site ever
// disagree, the catalog is stale, not the parser.

const bySlug = Object.fromEntries(catalog.skills.map((s) => [s.name, s]));

function useHash() {
  const [hash, setHash] = useState(() => window.location.hash.slice(1));
  useEffect(() => {
    const on = () => setHash(window.location.hash.slice(1));
    window.addEventListener("hashchange", on);
    return () => window.removeEventListener("hashchange", on);
  }, []);
  return hash;
}

const bytes = (n) =>
  n >= 1 << 20 ? `${(n / (1 << 20)).toFixed(1)}M` : n >= 1024 ? `${(n / 1024).toFixed(1)}k` : `${n}B`;

const when = (iso) => {
  const d = (Date.now() - new Date(iso)) / 86400000;
  if (d < 1) return "today";
  if (d < 2) return "yesterday";
  if (d < 30) return `${Math.floor(d)} days ago`;
  return new Date(iso).toLocaleDateString(undefined, { day: "numeric", month: "short", year: "numeric" });
};

function Badges({ problems }) {
  if (!problems?.length) return <div className="badges"><span className="badge ok">healthy</span></div>;
  return (
    <div className="badges">
      {problems.map((p, i) => (
        <span key={i} className={`badge ${p.level === 1 ? "err" : "warn"}`} title={p.detail}>
          {p.code}
        </span>
      ))}
    </div>
  );
}

function Sidebar({ current }) {
  return (
    <nav className="sidebar">
      <a className="brand" href="#">
        skill-issue
        <small>
          {catalog.skills.length} skills · {catalog.groups.length} collections
        </small>
      </a>
      {catalog.groups.map((g) => (
        <div key={g}>
          <div className="group-label">{g}</div>
          {catalog.skills
            .filter((s) => s.group === g)
            .map((s) => (
              <a
                key={s.name}
                className={`nav-item${current === s.name ? " active" : ""}`}
                href={`#${s.name}`}
              >
                <span>{s.name}</span>
                {s.problems?.length ? (
                  <span className="dot" style={{ color: s.problems.some((p) => p.level === 1) ? "var(--err)" : "var(--warn)" }}>
                    ●
                  </span>
                ) : null}
              </a>
            ))}
        </div>
      ))}
    </nav>
  );
}

function Index() {
  const broken = catalog.problems?.length ?? 0;
  return (
    <main>
      <h1>skill-issue</h1>
      <p className="lede">
        Our own library of agent skills. Every skill is a folder with a SKILL.md; the
        first tag decides which collection it lives in. This page and the TUI read the
        same generated catalog, so they never disagree.
      </p>
      <div className="meta">
        <span><b>skills</b> {catalog.skills.length}</span>
        <span><b>collections</b> {catalog.groups.length}</span>
        <span><b>problems</b> {broken}</span>
        <span><b>generated</b> {when(catalog.generated)}</span>
      </div>

      {catalog.groups.map((g) => (
        <section key={g}>
          <h2>{g}</h2>
          <p className="section-intro">
            {catalog.skills.filter((s) => s.group === g).length} skill(s) tagged <code>{g}</code>
          </p>
          {catalog.skills
            .filter((s) => s.group === g)
            .map((s) => (
              <a className="card" key={s.name} href={`#${s.name}`}>
                <div className="card-name">{s.name}</div>
                <div className="card-desc">{s.description || "— no description, so this skill never loads —"}</div>
              </a>
            ))}
        </section>
      ))}
      <p className="footer-note">generated by `skill-issue catalog` from {catalog.skills.length} folders</p>
    </main>
  );
}

function Skill({ s }) {
  return (
    <main>
      <h1>{s.name}</h1>
      <div className="meta">
        <span><b>collection</b> {s.group}</span>
        <span><b>files</b> {s.files.length}</span>
        <span><b>size</b> {bytes(s.size)}</span>
        <span><b>updated</b> {when(s.updated)}</span>
        <span><b>hash</b> {s.hash}</span>
      </div>
      <div className="badges" style={{ marginBottom: 10 }}>
        {s.tags?.map((t) => (
          <span className="tag" key={t}>
            {t}
          </span>
        ))}
      </div>
      <p className="lede">{s.description || "No description. This skill will never load."}</p>
      <Badges problems={s.problems} />

      <div className="prose" dangerouslySetInnerHTML={{ __html: marked.parse(stripH1(s.body)) }} />

      <h2>Bundled files</h2>
      <div className="files">
        {s.files.map((f) => (
          <div key={f.Rel}>
            {f.Rel} <span className="size">{bytes(f.Size)}</span>
          </div>
        ))}
      </div>

      <p className="footer-note">{s.path}/SKILL.md</p>
    </main>
  );
}

// The page already shows the name as its H1; a second one in the body is noise.
function stripH1(body) {
  return body.replace(/^#\s+.*\n/, "");
}

export default function App() {
  const hash = useHash();
  const s = bySlug[hash];
  return (
    <div className="layout">
      <Sidebar current={hash} />
      {s ? <Skill s={s} /> : <Index />}
    </div>
  );
}
