import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// The catalog lives at the repo root, one level above web/. It is generated by
// `si catalog`, so the site has no build step of its own that reads skills/.
export default defineConfig({
  base: "./",
  plugins: [react()],
  // Honour PORT so a supervising harness can place the dev server.
  server: { port: Number(process.env.PORT) || 5173, fs: { allow: [".."] } },
});
